import { writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import {
  chapters,
  lessons,
  items,
  courseSteps,
  extraSteps,
  classSteps,
} from "../../src/curriculum.js";
import { coverage } from "../../src/content/assemble.js";
import { objectives } from "../../src/content/objectives.js";
import { vocabulary } from "../../src/content/vocabulary.js";
const line = (text) => text.replaceAll("|", "/").replaceAll("\n", " ");
for (const [ch, title, ids] of objectives)
  for (const id of ids)
    assert.ok(
      lessons.some((l) => l.id === id && l.chapter === ch - 1),
      `${title}: ${id}`,
    );
for (const [ch, , title, raw] of vocabulary)
  for (const entry of raw.split(";")) {
    const [lt, en] = entry.trim().split("|");
    assert.ok(
      items.some((i) => i.lt.toLowerCase() === lt.toLowerCase() && i.en === en),
      `${title}: ${lt}`,
    );
  }
let out = `# LANGAS coverage ledger\n\nGenerated by \`npm run content:coverage\`. Source: the supplied fifth-edition LANGAS PDF. Page numbers are printed pages.\n\n## Scope\n\nThe main path now teaches the chapter vocabulary inventories, explicit grammar families and communicative objectives represented below, with original English guidance and original text activities. The expanded country/language appendix is optional practice, available in Your course without blocking progression. The alphabet and grammar tables are available as a collapsed study reference.\n\nThis is a text adaptation: audio, pronunciation assessment, song performance, partner speaking and licensed imagery are excluded. Listening-information objectives receive text-based counterparts. Open writing uses a saved draft, model and checklist; it is self-reviewed, not automatically grammar-graded. The ledger establishes authored coverage, not validated A1 proficiency or a word-for-word reproduction of every printed task or incidental glossary entry.\n\n## Volume\n\n${lessons.filter((l) => !l.optional).length} main-path classes; ${courseSteps.length} scheduled main-path sessions; ${lessons.filter((l) => l.optional).length} optional appendix classes with ${extraSteps.length} sessions; ${items.length} target entries across both. Entries count words, forms, sentences, reading questions and writing prompts—not unique lemmas.\n\n| Chapter | Main classes | Main sessions | Targets (including optional) | Reading situations | Writing |\n|---|---:|---:|---:|---:|---:|\n`;
chapters.forEach(
  (ch, n) =>
    (out += `| ${n + 1}. ${ch.title} | ${lessons.filter((l) => l.chapter === n && !l.optional).length} | ${courseSteps.filter((s) => s.chapter === n).length} | ${items.filter((i) => i.chapter === n).length} | ${lessons.filter((l) => l.chapter === n && l.kind === "reading").length} | ${lessons.filter((l) => l.chapter === n && l.kind === "writing").length} |\n`),
);
out +=
  "\n## Communicative objective mapping\n\nEach objective has teaching or assessment counterparts. See the class inventory below for source pages and visit counts.\n\n| Chapter | PDF objective | Classes |\n|---|---|---|\n";
for (const [ch, title, ids] of objectives)
  out += `| ${ch} | ${line(title)} | ${ids.map((id) => "`" + id + "`").join(", ")} |\n`;
out +=
  "\n## Added vocabulary and grammar inventory\n\nAll added lexical inventory rows are checked against the executable course bank. Duplicate identical entries may be taught in another class. Source provenance is chapter-level or topic-level; original situations are adaptations of the cited task objectives, not quotations.\n\n| Chapter | Class | Source pages | Approach | Visits | Core targets |\n|---|---|---|---|---:|---|\n";
for (const c of coverage)
  out += `| ${c.chapter} | ${line(c.title)} (\`${c.id}\`) | ${c.sourcePages} | ${c.kind}${lessons.find((l) => l.id === c.id)?.optional ? " (optional)" : ""} | ${classSteps(c.id).length} | ${c.targets.map((t) => line(t.lt)).join("; ")} |\n`;
out +=
  "\n## Progress and assessment\n\nOriginal word and ordinary lesson IDs are retained. New application visits for the 23 previously context-free classes have new step IDs, so an old application pass does not award the new work. Historical chapter-check events remain readable; expanded checks use new IDs. Each check section samples two targets per class from at most four classes. Retakes prioritise less-tested targets and weaker support levels rather than always asking the same first/last pair. All sections and teaching visits must be completed to finish the main path. Self-reviewed writing never contributes to automatic word mastery.\n\n## Remaining validation\n\nNative-speaker review and actual delayed-retention observation remain necessary. The app still uses item-level learning records rather than a complete model of morphological knowledge. This content pass does not claim that every accepted Lithuanian paraphrase is covered or that every textbook glossary surface form is independently drilled.\n";
await writeFile("docs/langas-coverage.md", out);
console.log(
  `Validated ${objectives.length} communicative objective mappings and ${vocabulary.length} lexical inventories. Wrote docs/langas-coverage.md.`,
);
