import { writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import {
  chapters,
  lessons,
  items,
  courseSteps,
  extraSteps,
  classSteps,
} from "../../src/curriculum.js";
import { coverage } from "../../src/content/assemble.js";
import { objectives } from "../../src/content/objectives.js";
import { vocabulary } from "../../src/content/vocabulary.js";
const line = (text) => text.replaceAll("|", "/").replaceAll("\n", " ");
for (const [ch, title, ids] of objectives)
  for (const id of ids)
    assert.ok(
      lessons.some((l) => l.id === id && l.chapter === ch - 1),
      `${title}: ${id}`,
    );
for (const [ch, , title, raw] of vocabulary)
  for (const entry of raw.split(";")) {
    const [lt, en] = entry.trim().split("|");
    assert.ok(
      items.some((i) => i.lt.toLowerCase() === lt.toLowerCase() && i.en === en),
      `${title}: ${lt}`,
    );
  }
let out = `# Curriculum coverage ledger\n\nGenerated by \`npm run content:coverage\`. This inventory validates authored vocabulary and objective mappings, not language proficiency.\n\n${lessons.filter((l) => !l.optional).length} main classes; ${courseSteps.length} main sessions; ${items.length} target entries. Entries include words, forms, sentences, reading questions and writing prompts.\n\n| Chapter | Main classes | Main sessions | Targets (including optional) | Reading situations | Writing |\n|---|---:|---:|---:|---:|---:|\n`;
chapters.forEach(
  (ch, n) =>
    (out += `| ${n + 1}. ${ch.title} | ${lessons.filter((l) => l.chapter === n && !l.optional).length} | ${courseSteps.filter((s) => s.chapter === n).length} | ${items.filter((i) => i.chapter === n).length} | ${lessons.filter((l) => l.chapter === n && l.kind === "reading").length} | ${lessons.filter((l) => l.chapter === n && l.kind === "writing").length} |\n`),
);
out +=
  "\n## Communicative objective mapping\n\nEach objective has teaching or assessment counterparts. See the class inventory below for source pages and visit counts.\n\n| Chapter | Learning objective | Classes |\n|---|---|---|\n";
for (const [ch, title, ids] of objectives)
  out += `| ${ch} | ${line(title)} | ${ids.map((id) => "`" + id + "`").join(", ")} |\n`;
out +=
  "\n## Added vocabulary and grammar inventory\n\nAll added lexical inventory rows are checked against the executable course bank. Duplicate identical entries may be taught in another class. \n\n| Chapter | Class | Approach | Visits | Core targets |\n|---|---|---|---:|---|\n";
for (const c of coverage)
  out += `| ${c.chapter} | ${line(c.title)} (\`${c.id}\`) | ${c.kind}${lessons.find((l) => l.id === c.id)?.optional ? " (optional)" : ""} | ${classSteps(c.id).length} | ${c.targets.map((t) => line(t.lt)).join("; ")} |\n`;
out +=
  "\n## Progress and assessment\n\nOriginal word and ordinary lesson IDs are retained. New application visits for the 23 previously context-free classes have new step IDs, so an old application pass does not award the new work. Historical chapter-check events remain readable; expanded checks use new IDs. Each check section samples two targets per class from at most four classes. Retakes prioritise less-tested targets and weaker support levels rather than always asking the same first/last pair. All sections and teaching visits must be completed to finish the main path. Self-reviewed writing never contributes to automatic word mastery.\n\n## Remaining validation\n\nNative-speaker review and actual delayed-retention observation remain necessary. The app still uses item-level learning records rather than a complete model of morphological knowledge. This content pass does not claim that every accepted Lithuanian paraphrase is covered or that every possible surface form is independently drilled.\n";
await writeFile("docs/coverage.md", out);
console.log(
  `Validated ${objectives.length} communicative objective mappings and ${vocabulary.length} lexical inventories. Wrote docs/coverage.md.`,
);
