// New model sentences for lexical groups. They introduce useful combinations;
// situation lessons subsequently test comprehension without showing an answer list.
export const applications = {
  "People and personal details": `Mano pavardė Kazlauskas|My surname is Kazlauskas|vocabulary|Mano ___ Kazlauskas\nJi yra mano dėstytoja|She is my lecturer|vocabulary|Ji yra mano ___`,
  "Your first places": `Aš gyvenu bendrabutyje|I live in a dormitory|locative|Aš gyvenu ___\nUniversitetas yra centre|The university is in the centre|locative|Universitetas yra ___`,
  "People and possession": `Mūsų draugai gyvena Vilniuje|Our friends live in Vilnius|pronouns|___ draugai gyvena Vilniuje\nJos vardas Lina|Her name is Lina|pronouns|___ vardas Lina`,
  "Ask and understand": `Aš truputį suprantu|I understand a little|vocabulary|Aš ___ suprantu\nKur yra universitetas?|Where is the university?|phrases`,
  "Useful first replies": `Atsiprašau, aš nesuprantu|Sorry, I do not understand|phrases\nAčiū, jums taip pat|Thank you, you too (formal)|phrases`,
  "Meat and fish": `Norėčiau vištienos|I would like chicken|genitive|Norėčiau ___\nMan patinka kepta žuvis|I like fried fish|adjectives|Man patinka ___ žuvis`,
  "Bread and dairy": `Sumuštinis su sviestu|A sandwich with butter|instrumental|Sumuštinis su ___\nPrašom bandelės su varške|A bun with curd cheese, please|instrumental|Prašom bandelės su ___`,
  "Vegetable basket": `Sriuba su kopūstais|Soup with cabbage|instrumental|Sriuba su ___\nPrašom virtų bulvių|Boiled potatoes, please|genitive|Prašom virtų ___`,
  "Fruit basket": `Norėčiau apelsinų sulčių|I would like orange juice|genitive|Norėčiau ___ sulčių\nMan patinka braškės|I like strawberries|plural|Man patinka ___`,
  "Dessert and the cupboard": `Arbata su medumi|Tea with honey|instrumental|Arbata su ___\nNorėčiau šokolado|I would like some chocolate|genitive|Norėčiau ___`,
  "On the menu": `Kokia dienos sriuba?|What is the soup of the day?|phrases\nPrašom ryžių ir salotų|Rice and salad, please|genitive|Prašom ryžių ir ___`,
  "Describe a flavour": `Kava per stipri|The coffee is too strong|adjectives|Kava per ___\nSaldus pyragas|A sweet pie|adjectives|___ pyragas`,
  "How food is prepared": `Norėčiau šviežios duonos|I would like fresh bread|genitive|Norėčiau ___ duonos\nSriuba per karšta|The soup is too hot|adjectives|Sriuba per ___`,
  "Paying and café signs": `Mokėsiu grynaisiais|I will pay in cash|instrumental|Mokėsiu ___\nKavos išsinešti, prašom|Coffee to take away, please|phrases`,
  "Food and drink actions": `Ar norite valgyti?|Do you want to eat (formal)?|present|Ar ___ valgyti?\nKaip mokėsite?|How will you pay (formal)?|phrases`,
  Landmarks: `Rotušė yra aikštėje|The town hall is in the square|locative|Rotušė yra ___\nPrie bažnyčios yra paminklas|There is a monument by the church|genitive|Prie ___ yra paminklas`,
  "Errands in town": `Einu į paštą|I am going to the post office|accusative|Einu į ___\nBankomatas yra prie parduotuvės|The ATM is beside the shop|genitive|Bankomatas yra prie ___`,
  "Public transport": `Prašom parodyti bilietą|Please show the ticket|accusative|Prašom parodyti ___\nPrašom sustoti prie stoties|Please stop by the station|genitive|Prašom sustoti prie ___`,
  "Directions and movement": `Eikite tiesiai iki pašto|Go straight as far as the post office (formal)|genitive|Eikite tiesiai iki ___\nPrie banko pasukite į dešinę|Turn right at the bank (formal)|phrases`,
  "When and how often": `Aš kasdien einu į universitetą|I go to university every day|vocabulary|Aš ___ einu į universitetą\nKartais važiuoju taksi|I sometimes take a taxi|vocabulary|___ važiuoju taksi`,
  "Rooms and buildings": `Mano kambarys yra koridoriaus gale|My room is at the end of the corridor|genitive|Mano kambarys yra ___ gale\nKur yra liftas?|Where is the lift?|phrases`,
  "Furnishing a home": `Prie sofos yra fotelis|There is an armchair beside the sofa|genitive|Prie ___ yra fotelis\nKompiuteris yra ant stalo|The computer is on the table|genitive|Kompiuteris yra ant ___`,
  "Household essentials": `Man reikia rankšluosčio|I need a towel|genitive|Man reikia ___\nVeidrodis yra vonioje|The mirror is in the bathroom|locative|Veidrodis yra ___`,
  "Describe your flat": `Mano butas mažas, bet jaukus|My flat is small but cosy|adjectives|Mano butas mažas, bet ___\nVirtuvė švari ir šviesi|The kitchen is clean and bright|adjectives|Virtuvė švari ir ___`,
  "Things to do at home": `Reikia išjungti kompiuterį|The computer needs to be switched off|accusative|Reikia išjungti ___\nNoriu išsinuomoti kambarį|I want to rent a room|accusative|Noriu išsinuomoti ___`,
  "Arts and evenings out": `Prašom du bilietus į operą|Two tickets to the opera, please|accusative|Prašom du bilietus į ___\nKuri eilė?|Which row?|phrases`,
  "Sport and the outdoors": `Mėgstu žaisti tenisą|I like playing tennis|accusative|Mėgstu žaisti ___\nVasarą važiuosiu prie jūros|In summer I will go to the seaside|genitive|Vasarą važiuosiu prie ___`,
  "Travelling and the seasons": `Traukinys išvyksta iš antro perono|The train leaves from the second platform|genitive|Traukinys išvyksta iš antro ___\nRudenį atostogausiu|I will be on holiday in autumn|accusative|___ atostogausiu`,
  "Holiday actions": `Vakar išsiunčiau atviruką|Yesterday I sent a postcard|past|Vakar ___ atviruką\nRytoj grįšime namo|Tomorrow we will return home|future|Rytoj ___ namo`,
  "Hobbies in words": `Aš mėgstu važinėti dviračiu|I like riding a bicycle|instrumental|Aš mėgstu važinėti ___\nJi moka slidinėti|She knows how to ski|present|Ji ___ slidinėti`,
  "University life": `Egzaminas bus raštu|The exam will be written|phrases\nPo seminaro bus pertrauka|There will be a break after the seminar|genitive|Po ___ bus pertrauka`,
  "Study tasks and equipment": `Reikia rengti prezentaciją|A presentation needs to be prepared|accusative|Reikia rengti ___\nKoks puslapis?|Which page?|phrases`,
  "Subjects to study": `Ji studijuoja žurnalistiką|She studies journalism|accusative|Ji studijuoja ___\nJis studijuoja istoriją|He studies history|accusative|Jis studijuoja ___`,
  "Managing your studies": `Atsiprašau, kad vėluoju|Sorry that I am late|phrases\nPrašom palaukti|Please wait|phrases`,
  "At work": `Prašom pasirašyti sutartį|Please sign the contract|accusative|Prašom pasirašyti ___\nNorėčiau kalbėti su direktore|I would like to speak to the director (female)|instrumental|Norėčiau kalbėti su ___`,
  Professions: `Mano mama yra inžinierė|My mother is an engineer|vocabulary|Mano mama yra ___\nMano tėtis yra vairuotojas|My father is a driver|vocabulary|Mano tėtis yra ___`,
  "A working day": `Direktorė išvyko į komandiruotę|The director (female) left on a business trip|accusative|Direktorė išvyko į ___\nAr galite paskambinti vėliau?|Can you call later (formal)?|phrases`,
  "People and family status": `Mano sesuo neištekėjusi|My sister is unmarried|adjectives|Mano sesuo ___\nMano brolis vedęs|My brother is married|adjectives|Mano brolis ___`,
  "The extended family": `Mano teta turi dukterį|My aunt has a daughter|accusative|Mano teta turi ___\nSenelis skambina anūkui|Grandfather calls his grandson|dative|Senelis skambina ___`,
  "Family events and actions": `Sesuo gimė Kaune|My sister was born in Kaunas|past|Sesuo ___ Kaune\nPer vestuves šokome|We danced at the wedding|accusative|Per ___ šokome`,
  "Describe appearance": `Ji yra vidutinio amžiaus|She is middle-aged|adjectives\nMano brolis panašus į tėtį|My brother looks like my father|accusative|Mano brolis panašus į ___`,
  "Describe character": `Mano draugė labai nuoširdi|My friend (female) is very sincere|adjectives|Mano draugė labai ___\nJis darbštus ir mandagus|He is hard-working and polite|adjectives|Jis darbštus ir ___`,
  "Weather forecast": `Pučia šiaurės vėjas|A north wind is blowing|genitive|Pučia ___ vėjas\nRytoj bus šlapdriba|There will be sleet tomorrow|vocabulary|Rytoj bus ___`,
  "Clothes for every day": `Man reikia naujo palto|I need a new coat|genitive|Man reikia naujo ___\nPerku striukę|I am buying a jacket|accusative|Perku ___`,
  "Shoes and accessories": `Pasiimsiu skėtį|I will take an umbrella|accusative|Pasiimsiu ___\nMan reikia pirštinių|I need gloves|genitive|Man reikia ___`,
  "Materials and labels": `Megztinis yra vilnonis|The sweater is woollen|adjectives|Megztinis yra ___\nAr turite kvitą?|Do you have the receipt (formal)?|accusative|Ar turite ___?`,
  "Colour and fit": `Striukė per trumpa|The jacket is too short|adjectives|Striukė per ___\nNorėčiau pilko megztinio|I would like a grey sweater|genitive|Norėčiau ___ megztinio`,
  "Shopping actions": `Norėčiau grąžinti suknelę|I would like to return the dress|accusative|Norėčiau grąžinti ___\nPrašom pridėti kortelę|Please tap your card|accusative|Prašom pridėti ___`,
  "The body": `Man skauda nugarą|My back hurts|accusative|Man skauda ___\nJam skauda ausį|His ear hurts|accusative|Jam skauda ___`,
  "Illness and symptoms": `Aš peršalau|I caught a cold|past|Aš ___\nJi kosėja|She is coughing|present|Ji ___`,
  "People at the clinic": `Noriu užsiregistruoti pas odontologą|I want to make a dentist’s appointment|accusative|Noriu užsiregistruoti pas ___\nKur yra rentgeno kabinetas?|Where is the X-ray room?|phrases`,
  "At the pharmacy counter": `Ar turite sveikatos draudimą?|Do you have health insurance (formal)?|accusative|Ar turite sveikatos ___?\nPrašom vaistų nuo kosulio|Some cough medicine, please|genitive|Prašom vaistų nuo ___`,
  "Family celebrations": `Kviečiu jus į krikštynas|I invite you to a christening (formal)|accusative|Kviečiu jus į ___\nKas pasakys tostą?|Who will make a toast?|phrases`,
  "Spring celebrations": `Per Velykas dažome kiaušinius|At Easter we colour eggs|accusative|Per Velykas dažome ___\nEiname į Kaziuko mugę|We are going to Kaziukas Fair|accusative|Einame į Kaziuko ___`,
  "Summer and autumn celebrations": `Per Vėlines einame į kapines|On All Souls’ Day we go to the cemetery|accusative|Per Vėlines einame į ___\nPer Jonines piname vainikus|At Midsummer we weave wreaths|accusative|Per Jonines piname ___`,
  "Christmas traditions": `Per Kūčias valgome kūčiukus|On Christmas Eve we eat kūčiukai|accusative|Per Kūčias valgome ___\nPuošiame Kalėdų eglę|We decorate the Christmas tree|accusative|Puošiame Kalėdų ___`,
  "Wishes and feelings": `Linkiu geros nuotaikos|I wish you a good mood|genitive|Linkiu geros ___\nNuoširdžiai sveikinu|I sincerely congratulate you|vocabulary|___ sveikinu`,
};
Object.assign(applications, {
  "Lithuanian dishes":
    "Norėčiau cepelinų su grybais|I would like potato dumplings with mushrooms|instrumental|Norėčiau cepelinų su ___\nMan patinka šaltibarščiai|I like cold beetroot soup|plural|Man patinka ___",
  "Food and traditions":
    "Miške yra grybų|There are mushrooms in the forest|genitive|Miške yra ___\nSūris su uogiene|Cheese with jam|instrumental|Sūris su ___",
  "Everyday public signs":
    "Kada prasideda darbo laikas?|When do opening hours begin?|phrases\nBankomatas dabar neveikia|The ATM is not working now|present|Bankomatas dabar ___",
  "Signs in a building":
    "Durys uždarytos|The doors are closed|adjectives|Durys ___\nPrašom atidaryti duris|Please open the door|accusative|Prašom atidaryti ___",
  "Time around a trip":
    "Pernai atostogavome prie jūros|Last year we holidayed by the sea|past|Pernai ___ prie jūros\nPoryt išvyksiu|I will leave the day after tomorrow|future|Poryt ___",
  "Signs at work and university":
    "Dekanatas yra pirmame aukšte|The dean’s office is on the first floor|locative|Dekanatas yra ___ aukšte\nDabar pietų pertrauka|It is lunch break now|phrases",
  "Read shop signs":
    "Kur yra matavimosi kabinos?|Where are the fitting rooms?|phrases\nAr galiu mokėti grynaisiais?|Can I pay in cash?|instrumental|Ar galiu mokėti ___?",
  "Find your way in a clinic":
    "Kur yra registratūra?|Where is reception?|phrases\nReikia kviesti greitąją pagalbą|An ambulance needs to be called|accusative|Reikia kviesti greitąją ___",
});
