// Original text-only counterparts to LANGAS communicative and reading objectives.
// Questions carry curated alternatives; every answer is supported by the passage.
// chapter, key, title, source pages, passage, [question, answer, meaning, distractors].
export const situations = [
  [
    1,
    "classmate",
    "Read a classmate’s introduction",
    "19–23",
    `Labas! Mano vardas Lina. Aš esu studentė. Esu iš Latvijos, bet dabar gyvenu Vilniuje. Kalbu latviškai ir angliškai. Lietuviškai suprantu truputį.`,
    [
      ["What is her name?", "Lina", "Lina", ["Rasa", "Jonas"]],
      [
        "Where does she live now? Answer with the city in its location form.",
        "Vilniuje",
        "In Vilnius",
        ["Rygoje", "Kaune"],
      ],
      [
        "Complete: Lietuviškai ji supranta ___.",
        "truputį",
        "a little",
        ["gerai", "labai gerai"],
      ],
    ],
  ],
  [
    1,
    "reception",
    "Give information at reception",
    "19–20",
    `Administratorė: Koks jūsų vardas ir pavardė?\nStudentas: Mantas Petrauskas.\nAdministratorė: Kur gyvenate?\nStudentas: Kaune, Parko gatvėje.\nAdministratorė: Ar jūs dirbate?\nStudentas: Ne, aš studijuoju.`,
    [
      [
        "Which surname should be entered on the form?",
        "Petrauskas",
        "Petrauskas",
        ["Mantas", "Parko"],
      ],
      [
        "Complete the student’s reply: Ne, aš ___.",
        "studijuoju",
        "I study",
        ["dirbu", "gyvenu"],
      ],
      [
        "Which question asked where he lives?",
        "Kur gyvenate?",
        "Where do you live (formal)?",
        ["Kas jūs esate?", "Kaip sekasi?"],
      ],
    ],
  ],
  [
    2,
    "menu",
    "Choose from a café menu",
    "33–34, 57–58",
    `MENIU\nPomidorų sriuba – 3,20 Eur\nGrybų sriuba – 4,10 Eur\nKava su pienu – 2,50 Eur\nArbata – 2,00 Eur\nObuolių pyragas – 3,00 Eur`,
    [
      [
        "Which soup costs €3.20?",
        "Pomidorų sriuba",
        "Tomato soup",
        ["Grybų sriuba", "Obuolių pyragas"],
      ],
      [
        "Which drink costs €2.00?",
        "Arbata",
        "Tea",
        ["Kava su pienu", "Grybų sriuba"],
      ],
      [
        "Say the price of coffee in words.",
        "Du eurai penkiasdešimt centų",
        "Two euros and fifty cents",
        ["Trys eurai dvidešimt centų", "Keturi eurai dešimt centų"],
      ],
    ],
  ],
  [
    2,
    "cafe-exchange",
    "Order, refuse, and pay",
    "34, 40–42",
    `Padavėja: Ko norėtumėte?\nKlientas: Norėčiau daržovių sriubos ir arbatos.\nPadavėja: Arbatos su cukrumi?\nKlientas: Ne, be cukraus.\nPadavėja: Dar ko nors?\nKlientas: Ne, ačiū. Sąskaitą, prašom. Mokėsiu kortele.`,
    [
      [
        "Complete the request: Norėčiau daržovių ___.",
        "sriubos",
        "soup (genitive)",
        ["sriuba", "sriubą"],
      ],
      [
        "Does he want sugar? Give his short answer.",
        "Ne, be cukraus",
        "No, without sugar",
        ["Taip, su cukrumi", "Ne, be pieno"],
      ],
      ["How will he pay?", "Kortele", "By card", ["Grynaisiais", "Eurais"]],
    ],
  ],
  [
    2,
    "host-drink",
    "Accept an offer and compliment food",
    "34",
    `Šeimininkė: Ar norite kavos?\nSvečias: Ačiū, nenoriu. Gal galima arbatos?\nŠeimininkė: Žinoma. Prašom pyrago.\nSvečias: Ačiū, labai skanu!\nŠeimininkė: Gero apetito!`,
    [
      [
        "Which drink does the guest ask for? Use the request form.",
        "Arbatos",
        "Some tea",
        ["Kavos", "Vandens"],
      ],
      [
        "Which phrase politely refuses the coffee?",
        "Ačiū, nenoriu",
        "Thank you, I do not want any",
        ["Gero apetito", "Labai skanu"],
      ],
      [
        "Which phrase compliments the food?",
        "Labai skanu",
        "Very tasty",
        ["Gal galima", "Žinoma"],
      ],
    ],
  ],
  [
    3,
    "directions",
    "Follow written directions",
    "70–71",
    `Iki pašto eikite tiesiai. Prie pašto pasukite į kairę. Bankas yra dešinėje, prie knygyno. Muziejus yra prie upės.`,
    [
      [
        "Which way do you turn at the post office?",
        "Į kairę",
        "To the left",
        ["Į dešinę", "Tiesiai"],
      ],
      [
        "What is beside the bank? Use the dictionary form.",
        "Knygynas",
        "Bookshop",
        ["Muziejus", "Upė"],
      ],
      [
        "Complete: Muziejus yra prie ___.",
        "upės",
        "river (genitive)",
        ["upė", "upę"],
      ],
    ],
  ],
  [
    3,
    "meeting-message",
    "Arrange a meeting from a message",
    "66, 70–71",
    `Rasa: Susitinkame šeštadienį?\nTomas: Gerai. Pusę trečios prie muziejaus?\nRasa: Puiku. Važiuosiu autobusu.\nTomas: O aš eisiu pėsčiomis. Iki šeštadienio!`,
    [
      [
        "On which day are they meeting?",
        "Šeštadienį",
        "On Saturday",
        ["Sekmadienį", "Penktadienį"],
      ],
      [
        "What time have they agreed? Use the phrase from the message.",
        "Pusę trečios",
        "At half past two",
        ["Trečią valandą", "Pusę antros"],
      ],
      [
        "How will Tomas get there?",
        "Pėsčiomis",
        "On foot",
        ["Autobusu", "Traukiniu"],
      ],
    ],
  ],
  [
    3,
    "transport-signs",
    "Read signs and use a ticket",
    "65, 70",
    `STOTELĖ: CENTRAS\n2 autobusas → Stotis\n5 autobusas → Oro uostas\nBilietų automatas neveikia.\nKioske: Prašom papildyti elektroninį bilietą.`,
    [
      [
        "Which bus goes to the airport?",
        "Penktas autobusas",
        "The fifth bus",
        ["Antras autobusas", "Pirmas autobusas"],
      ],
      [
        "Complete the sign: Bilietų automatas ___.",
        "neveikia",
        "is not working",
        ["dirba", "važiuoja"],
      ],
      [
        "What can you ask at the kiosk?",
        "Prašom papildyti elektroninį bilietą",
        "Please top up the electronic ticket",
        ["Prašom sąskaitą", "Prašom uždaryti duris"],
      ],
    ],
  ],
  [
    4,
    "rental-ad",
    "Read a flat advertisement",
    "93–94, 106–108",
    `NUOMOJAMAS BUTAS\nDu kambariai, penktas aukštas. Yra balkonas ir internetas. Virtuvėje yra šaldytuvas. Lifto nėra. Nuoma – 450 eurų per mėnesį.`,
    [
      [
        "How many rooms does the flat have?",
        "Du kambariai",
        "Two rooms",
        ["Trys kambariai", "Vienas kambarys"],
      ],
      [
        "On which floor is it? Use a location phrase.",
        "Penktame aukšte",
        "On the fifth floor",
        ["Pirmame aukšte", "Antrame aukšte"],
      ],
      [
        "Complete: Bute nėra ___.",
        "lifto",
        "a lift (genitive)",
        ["balkono", "interneto"],
      ],
    ],
  ],
  [
    4,
    "home-help",
    "Explain a household problem",
    "89, 94",
    `Gyventoja: Gal galite padėti? Vonioje nėra karšto vandens.\nAdministratorius: Kelintas kambarys?\nGyventoja: Dvyliktas.\nAdministratorius: Kviečiu santechniką. Jis bus po pietų.`,
    [
      [
        "Which room number does she give?",
        "Dvyliktas",
        "Twelfth",
        ["Dvidešimtas", "Antras"],
      ],
      [
        "Complete the problem: Nėra karšto ___.",
        "vandens",
        "water (genitive)",
        ["vanduo", "vandenį"],
      ],
      [
        "Who is the administrator calling? Use the object form.",
        "Santechniką",
        "A plumber",
        ["Gydytoją", "Padavėją"],
      ],
    ],
  ],
  [
    4,
    "guest",
    "Visit and compliment a home",
    "89, 93–94",
    `Šeimininkas: Prašom užeiti ir sėstis.\nViešnia: Ačiū. Koks jaukus butas! Ar galiu atidaryti langą?\nŠeimininkas: Taip, žinoma.\nViešnia: O kur mano raktas?\nŠeimininkas: Ant lentynos, prie durų.`,
    [
      [
        "Which phrase asks permission to open the window?",
        "Ar galiu atidaryti langą?",
        "May I open the window?",
        ["Kur mano raktas?", "Prašom sėstis"],
      ],
      [
        "Where is the key?",
        "Ant lentynos",
        "On the shelf",
        ["Prie lango", "Ant stalo"],
      ],
      [
        "Which word describes the flat?",
        "Jaukus",
        "Cosy (masculine)",
        ["Triukšmingas", "Šaltas"],
      ],
    ],
  ],
  [
    5,
    "event-ticket",
    "Find a performance and your seat",
    "115–116",
    `KONCERTO BILIETAS\nPenktadienis, 19.00\nDidžioji salė\nEilė: 8. Vieta: 12.\nKaina: 20 Eur.\nStudentams – nuolaida.`,
    [
      [
        "What is the row number? Answer in words.",
        "Aštunta eilė",
        "The eighth row",
        ["Dvylikta eilė", "Antra eilė"],
      ],
      [
        "What is the seat number?",
        "Dvylikta vieta",
        "The twelfth seat",
        ["Aštunta vieta", "Dvidešimta vieta"],
      ],
      [
        "Complete: Studentams yra ___.",
        "nuolaida",
        "a discount",
        ["eilė", "salė"],
      ],
    ],
  ],
  [
    5,
    "holiday-postcard",
    "Read a holiday postcard",
    "117–120",
    `Labas, Rasa! Vakar atvykome prie jūros. Važiavome traukiniu. Šiandien ilsimės paplūdimyje. Rytoj eisime pasivaikščioti. Grįšime sekmadienį. Linkėjimai iš Palangos!`,
    [
      [
        "How did they travel?",
        "Traukiniu",
        "By train",
        ["Lėktuvu", "Autobusu"],
      ],
      [
        "Complete: Rytoj ___ pasivaikščioti.",
        "eisime",
        "we will go",
        ["ėjome", "einame"],
      ],
      [
        "When will they return?",
        "Sekmadienį",
        "On Sunday",
        ["Šeštadienį", "Rytoj"],
      ],
    ],
  ],
  [
    5,
    "bus-ticket",
    "Buy a bus ticket",
    "121–123",
    `Keleivė: Prašom vieną bilietą į Kauną.\nKasininkas: Kada važiuosite?\nKeleivė: Rytoj rytą.\nKasininkas: Autobusas išvyksta devintą valandą iš trečios aikštelės.\nKeleivė: Ačiū.`,
    [
      [
        "Where is the passenger going?",
        "Į Kauną",
        "To Kaunas",
        ["Į Vilnių", "Prie jūros"],
      ],
      [
        "When does the bus leave?",
        "Devintą valandą",
        "At nine o’clock",
        ["Trečią valandą", "Pusę devintos"],
      ],
      [
        "Complete: Autobusas išvyksta iš trečios ___.",
        "aikštelės",
        "platform (genitive)",
        ["eilės", "gatvės"],
      ],
    ],
  ],
  [
    6,
    "timetable",
    "Read a university timetable",
    "135, 144–146",
    `PIRMADIENIS\n9.00–10.30 – istorijos paskaita, 12 auditorija\n10.30–10.45 – pertrauka\n10.45–12.15 – seminaras, 8 auditorija\nEgzaminas – gegužės 22 dieną, raštu.`,
    [
      [
        "Which room is used for the seminar?",
        "Aštunta auditorija",
        "The eighth classroom",
        ["Dvylikta auditorija", "Antra auditorija"],
      ],
      [
        "Will the exam be oral or written?",
        "Raštu",
        "Written",
        ["Žodžiu", "Per pertrauką"],
      ],
      [
        "Give the exam date in words.",
        "Gegužės dvidešimt antrą dieną",
        "On May twenty-second",
        ["Gegužės antrą dieną", "Birželio dvidešimt antrą dieną"],
      ],
    ],
  ],
  [
    6,
    "work-message",
    "Understand a workplace message",
    "135, 139–140",
    `Laba diena! Direktorius šiandien išvykęs į komandiruotę. Jis grįš rytoj. Prašom paskambinti po pietų arba parašyti elektroninį laišką. Sekretorė dirba nuo devintos iki penktos.`,
    [
      [
        "When will the director return?",
        "Rytoj",
        "Tomorrow",
        ["Šiandien", "Pirmadienį"],
      ],
      [
        "When should you call?",
        "Po pietų",
        "After lunch",
        ["Prieš pietus", "Naktį"],
      ],
      [
        "Complete: Sekretorė dirba nuo devintos iki ___.",
        "penktos",
        "five (genitive)",
        ["penktą", "penkta"],
      ],
    ],
  ],
  [
    6,
    "study-email",
    "Read a study update",
    "146",
    `Labas! Studijuoju mediciną antrame kurse. Paskaitos prasideda devintą valandą. Po paskaitų einu į biblioteką. Vakar rašėme testą. Gavau aštuonis. Birželį bus egzaminas žodžiu.`,
    [
      [
        "What does the writer study? Use the object form.",
        "Mediciną",
        "Medicine",
        ["Istoriją", "Teisę"],
      ],
      [
        "Which year of study?",
        "Antrame kurse",
        "In the second year",
        ["Pirmame kurse", "Trečiame kurse"],
      ],
      [
        "Complete: Vakar ___ testą.",
        "rašėme",
        "we wrote",
        ["rašysime", "rašome"],
      ],
    ],
  ],
  [
    7,
    "family-profile",
    "Read a family profile",
    "155, 164–166",
    `Mano vardas Ieva. Turiu du brolius ir vieną seserį. Sesuo Rūta ištekėjusi, turi dukterį. Vyresnis brolis Tomas gyvena Kaune. Jaunesnis brolis Mantas dar studijuoja. Mano tėvai gyvena Vilniuje.`,
    [
      [
        "How many brothers does Ieva have?",
        "Du brolius",
        "Two brothers (object form)",
        ["Vieną brolį", "Tris brolius"],
      ],
      ["Who is married?", "Rūta", "Rūta", ["Ieva", "Mantas"]],
      ["Who is still studying?", "Mantas", "Mantas", ["Tomas", "Rūta"]],
    ],
  ],
  [
    7,
    "family-comparison",
    "Use age and comparisons",
    "157–160",
    `Lina yra jaunesnė už brolį Tomą. Jai dvidešimt treji metai, o Tomui dvidešimt šešeri. Jų seseriai Rasai devyniolika metų. Rasa yra jauniausia.`,
    [
      [
        "How old is Lina?",
        "Dvidešimt treji metai",
        "Twenty-three years",
        ["Dvidešimt šešeri metai", "Devyniolika metų"],
      ],
      ["Who is the youngest?", "Rasa", "Rasa", ["Lina", "Tomas"]],
      [
        "Complete: Lina jaunesnė už ___.",
        "Tomą",
        "Tomas (accusative)",
        ["Tomas", "Tomui"],
      ],
    ],
  ],
  [
    8,
    "forecast",
    "Choose clothing for a forecast",
    "179, 184–185",
    `ŠEŠTADIENIS\nRytą – trys laipsniai šilumos, lietus.\nDieną – debesuota, stiprus vėjas.\nVakare – du laipsniai šalčio.\nRasa pasiims skėtį ir šiltą paltą.`,
    [
      [
        "What is the temperature in the evening?",
        "Du laipsniai šalčio",
        "Two degrees below zero",
        ["Trys laipsniai šilumos", "Du laipsniai šilumos"],
      ],
      [
        "Complete: Dieną bus stiprus ___.",
        "vėjas",
        "wind",
        ["lietus", "sniegas"],
      ],
      [
        "What will Rasa take for the rain? Use the dictionary form.",
        "Skėtis",
        "Umbrella",
        ["Sijonas", "Piniginė"],
      ],
    ],
  ],
  [
    8,
    "clothes-label",
    "Read a label and ask for a return",
    "179",
    `MEGZTINIS\nSpalva: mėlyna. Dydis: 40.\nSudėtis: vilna 80 %, medvilnė 20 %.\nKaina: 45 Eur.\nKlientė: Megztinis per mažas. Norėčiau pakeisti.\nPardavėja: Ar turite kvitą?`,
    [
      [
        "Which material makes up most of the sweater?",
        "Vilna",
        "Wool",
        ["Medvilnė", "Šilkas"],
      ],
      [
        "Why does the customer want to exchange it?",
        "Per mažas",
        "Too small (masculine)",
        ["Per didelis", "Per brangus"],
      ],
      [
        "What does the shop assistant ask to see? Use the object form.",
        "Kvitą",
        "Receipt",
        ["Kortelę", "Etiketę"],
      ],
    ],
  ],
  [
    9,
    "appointment",
    "Make and understand an appointment",
    "197, 200–201",
    `Registratorė: Laba diena. Kas atsitiko?\nPacientė: Skauda gerklę. Norėčiau užsiregistruoti pas šeimos gydytoją.\nRegistratorė: Galite ateiti rytoj, dešimtą valandą. Turėkite asmens dokumentą.\nPacientė: Ačiū.`,
    [
      [
        "What hurts? Use the form from the reply.",
        "Gerklę",
        "Throat (accusative)",
        ["Galvą", "Dantį"],
      ],
      [
        "When is the appointment?",
        "Rytoj, dešimtą valandą",
        "Tomorrow at ten o’clock",
        ["Šiandien, dešimtą valandą", "Rytoj, devintą valandą"],
      ],
      [
        "Which document is requested?",
        "Asmens dokumentą",
        "Identity document (object form)",
        ["Receptą", "Bilietą"],
      ],
    ],
  ],
  [
    9,
    "pharmacy-label",
    "Understand a fictional medicine label",
    "196, 204–206",
    `KALBOS PRATIMO PAVYZDYS\nVartoti po valgio, du kartus per dieną.\nPacientas: Ar šie vaistai receptiniai?\nVaistininkė: Taip. Ar turite receptą?\nPacientas: Taip, prašom.`,
    [
      [
        "According to this fictional label, before or after meals?",
        "Po valgio",
        "After meals",
        ["Prieš valgį", "Per valgį"],
      ],
      [
        "What frequency is written?",
        "Du kartus per dieną",
        "Twice a day",
        ["Vieną kartą per dieną", "Tris kartus per dieną"],
      ],
      [
        "What does the pharmacist ask for? Use the object form.",
        "Receptą",
        "Prescription",
        ["Bilietą", "Sąskaitą"],
      ],
    ],
  ],
  [
    9,
    "illness-message",
    "Explain an absence and express sympathy",
    "197, 199, 204",
    `Tomas: Negalėsiu ateiti į paskaitą, nes sergu. Vakar jaučiausi blogai, šiandien truputį geriau.\nRasa: Kaip gaila! Sveik greičiau. Kai pasveiksi, paskambink.`,
    [
      [
        "Which word introduces the reason for missing class?",
        "Nes",
        "Because",
        ["Bet", "Arba"],
      ],
      [
        "How does Tomas feel today compared with yesterday?",
        "Geriau",
        "Better",
        ["Blogiau", "Taip pat"],
      ],
      [
        "Which reply wishes recovery?",
        "Sveik greičiau",
        "Get well sooner",
        ["Kaip gaila", "Paskambink"],
      ],
    ],
  ],
  [
    10,
    "festival-notice",
    "Read a celebration programme",
    "231",
    `PAVASARIO ŠVENTĖ\nŠeštadienį, gegužės 16 dieną\n12.00 – mugė prie rotušės\n15.00 – koncertas parke\n18.00 – šokiai aikštėje\nĮėjimas nemokamas.`,
    [
      [
        "Where is the concert?",
        "Parke",
        "In the park",
        ["Prie rotušės", "Aikštėje"],
      ],
      ["What begins at noon?", "Mugė", "Fair", ["Koncertas", "Šokiai"]],
      [
        "Complete the notice: Įėjimas ___.",
        "nemokamas",
        "free of charge",
        ["mokamas", "uždarytas"],
      ],
    ],
  ],
  [
    10,
    "holiday-traditions",
    "Read about holiday traditions",
    "212–213, 227–230",
    `Per Kūčias šeima vakarieniauja kartu. Ant stalo yra kūčiukų ir silkės. Per Velykas dažome kiaušinius ir ridename margučius. Per Jonines dainuojame prie laužo.`,
    [
      [
        "Which holiday has decorated eggs? Use the form after per.",
        "Velykas",
        "Easter (accusative)",
        ["Kūčias", "Jonines"],
      ],
      [
        "Complete: Per Jonines dainuojame prie ___.",
        "laužo",
        "bonfire (genitive)",
        ["stalo", "kiaušinio"],
      ],
      [
        "Name one Christmas Eve food from the text in dictionary form.",
        "Kūčiukai",
        "Christmas Eve biscuits",
        ["Margutis", "Blynas"],
      ],
    ],
  ],
  [
    10,
    "birthday-invitation",
    "Reply to an invitation",
    "217–219",
    `Labas, Rasa! Kviečiu tave į gimtadienį šeštadienį, septintą valandą vakaro. Švęsime namie. Ar galėsi ateiti?\nRasa: Ačiū už kvietimą! Būtinai ateisiu. Su gimtadieniu!`,
    [
      [
        "When does the party start?",
        "Septintą valandą vakaro",
        "At seven in the evening",
        ["Septintą valandą ryto", "Šeštą valandą vakaro"],
      ],
      [
        "Which reply accepts the invitation?",
        "Būtinai ateisiu",
        "I will definitely come",
        ["Negalėsiu ateiti", "Galėsi ateiti?"],
      ],
      [
        "Complete: Kviečiu ___ į gimtadienį.",
        "tave",
        "you (informal, object form)",
        ["tu", "tau"],
      ],
    ],
  ],
];
