// Curated lexical objectives from LANGAS chapter vocabulary pages.
// These are teaching inventories, not automatically extracted PDF text.
// Each group is split into small classes by the course assembler.
export const vocabulary = [
  [
    1,
    15,
    "People and personal details",
    `vardas|first name;pavardė|surname;dėstytojas|lecturer (male);dėstytoja|lecturer (female);studentas|student (male);studentė|student (female);draugas|friend (male);draugė|friend (female);ponas|Mr;ponia|Mrs;grupė|group;adresas|address;telefono numeris|phone number`,
  ],
  [
    1,
    15,
    "Your first places",
    `miestas|city;centras|centre;butas|flat;universitetas|university;akademija|academy;senamiestis|old town;bendrabutis|dormitory;auditorija|classroom;gatvė|street`,
  ],
  [
    1,
    15,
    "People and possession",
    `aš|I;tu|you (informal singular);jis|he;ji|she;mes|we;jūs|you (formal or plural);jie|they (masculine or mixed group);jos|they (feminine);mano|my;tavo|your (informal singular);jo|his;jos|her;mūsų|our;jūsų|your (formal or plural);jų|their`,
  ],
  [
    1,
    15,
    "Ask and understand",
    `kas|who / what;koks|what / what kind (masculine);kokia|what / what kind (feminine);iš kur|from where;kur|where;ar|yes/no question marker;kaip|how;dabar|now;truputį|a little;būti|to be;nebūti|not to be;gyventi|to live;dirbti|to work;studijuoti|to study;kalbėti|to speak;suprasti|to understand;nulis|zero`,
  ],
  [
    1,
    14,
    "Useful first replies",
    `Labanakt!|Good night!;Gerai|Well;Labai gerai|Very well;Neblogai|Not bad;Sėkmės!|Good luck!;Jums taip pat|You too (formal);Nėra už ką|You are welcome;Atsiprašau|Excuse me / sorry;Nieko tokio|No problem;Gaila|It is a pity;Malonu|Nice to meet you;Man taip pat|Me too;Sveikinu!|Congratulations!;Į sveikatą!|Cheers!;Taip|Yes;Ne|No;Prašom pakartoti|Please repeat;Aš nežinau|I do not know;Aš nesuprantu|I do not understand`,
  ],
  [
    2,
    32,
    "Meat and fish",
    `žuvis|fish;lašiša|salmon;tunas|tuna;mėsa|meat;kiauliena|pork;jautiena|beef;vištiena|chicken meat;kumpis|ham;dešra|sausage;dešrelė|frankfurter`,
  ],
  [
    2,
    32,
    "Bread and dairy",
    `bandelė|bun;sumuštinis|sandwich;pieno produktai|dairy products;sviestas|butter;varškė|curd cheese;jogurtas|yogurt;grietinė|sour cream`,
  ],
  [
    2,
    32,
    "Vegetable basket",
    `bulvė|potato;burokėlis|beetroot;česnakas|garlic;kopūstas|cabbage;morka|carrot;paprika|bell pepper;svogūnas|onion;grybas|mushroom;kiaušinis|egg`,
  ],
  [
    2,
    32,
    "Fruit basket",
    `vaisiai|fruit;apelsinas|orange (fruit);braškė|strawberry;citrina|lemon;slyva|plum;vynuogė|grape;vyšnia|cherry`,
  ],
  [
    2,
    32,
    "Dessert and the cupboard",
    `saldumynai|sweets;ledai|ice cream;medus|honey;pyragas|pie;saldainis|sweet / candy;sausainis|biscuit;šokoladas|chocolate;druska|salt;majonezas|mayonnaise;dribsniai|cereal flakes`,
  ],
  [
    2,
    32,
    "On the menu",
    `maistas|food;gėrimai|drinks;patiekalas|dish;salotos|salad;pica|pizza;makaronai|pasta;ryžiai|rice;gira|kvass;alus|beer;vynas|wine;dienos sriuba|soup of the day;dienos pietūs|lunch special`,
  ],
  [
    2,
    32,
    "Describe a flavour",
    `skanus|tasty (masculine);skani|tasty (feminine);stiprus|strong (masculine);sausas|dry (masculine);saldus|sweet (masculine);sūrus|salty (masculine);pieninis|milk (adjective, masculine);šokoladinis|chocolate (adjective, masculine);vaisinis|fruit (adjective, masculine)`,
  ],
  [
    2,
    32,
    "How food is prepared",
    `virtas|boiled (masculine);keptas|fried / baked (masculine);rūkytas|smoked (masculine);karštas|hot (masculine);šaltas|cold (masculine);šviežias|fresh (masculine);senas|old (masculine);šviesus|light (masculine);tamsus|dark (masculine);gazuotas|sparkling (masculine);negazuotas|still / non-carbonated (masculine)`,
  ],
  [
    2,
    32,
    "Paying and café signs",
    `baras|bar;restoranas|restaurant;valgykla|canteen;tualetas|toilet;padavėjas|waiter;padavėja|waitress;sąskaita|bill;kaina|price;euras|euro;centas|cent;vegetaras|vegetarian (male);vegetarė|vegetarian (female);pigus|cheap (masculine);brangus|expensive (masculine);kortele|by card;grynaisiais|in cash;rezervuota|reserved;išsinešti|to take away`,
  ],
  [
    2,
    32,
    "Food and drink actions",
    `patikti|to be pleasing / to like;norėti|to want;valgyti|to eat;gerti|to drink;kainuoti|to cost;mokėti|to pay`,
  ],
  [
    3,
    64,
    "Landmarks",
    `sostinė|capital city;katedra|cathedral;rotušė|town hall;bokštas|tower;aikštė|square;bažnyčia|church;pilis|castle;namas|house;paminklas|monument;prospektas|avenue;tiltas|bridge;upė|river`,
  ],
  [
    3,
    64,
    "Errands in town",
    `turgus|market;kirpykla|hairdresser’s; naktinis klubas|nightclub;sporto klubas|gym;kioskas|kiosk;parduotuvė|shop;bankomatas|ATM;paštas|post office;vaistinė|pharmacy;knygynas|bookshop;kinas|cinema;biuras|office;darbas|work;ambasada|embassy`,
  ],
  [
    3,
    64,
    "Public transport",
    `autobusų stotis|bus station;geležinkelio stotis|railway station;oro uostas|airport;autobusas|bus;troleibusas|trolleybus;traukinys|train;metro|metro;tramvajus|tram;taksi|taxi;dviratis|bicycle;automobilis|car;automobilių aikštelė|car park;stotelė|stop;bilietas|ticket;elektroninis bilietas|electronic ticket;bauda|fine;kontrolierius|ticket inspector (male)`,
  ],
  [
    3,
    64,
    "Directions and movement",
    `čia|here;ten|there;arti|near;toli|far;namo|homewards;paskui|afterwards;po to|then;prie|near / beside;pas|to a person;į|to / into;iki|until / as far as;į kairę|to the left;į dešinę|to the right;kairėje|on the left;dešinėje|on the right;tiesiai|straight ahead;eiti|to go on foot;eiti pėsčiomis|to walk;nueiti|to reach on foot;pereiti gatvę|to cross the street;važiuoti|to travel by vehicle;nuvažiuoti|to reach by vehicle;pasukti|to turn;susitikti|to meet;reikėti|to need;parodyti|to show`,
  ],
  [
    3,
    64,
    "When and how often",
    `kada|when;kuo|by what means;šiandien|today;rytoj|tomorrow;dažnai|often;retai|rarely;visada|always;niekada|never;kasdien|every day;kartais|sometimes;diena|day;vakaras|evening;naktis|night;valanda|hour;minutė|minute;savaitė|week;savaitgalis|weekend`,
  ],
  [
    4,
    88,
    "Rooms and buildings",
    `namai|home;viešbutis|hotel;aukštas|floor / storey;svetainė|living room;miegamasis|bedroom;dušas|shower;tualetas|toilet;balkonas|balcony;koridorius|corridor;liftas|lift;durų kodas|door code;siena|wall;kiemas|yard;sodas|garden;medis|tree;kaimynas|neighbour (male);kaimynė|neighbour (female)`,
  ],
  [
    4,
    88,
    "Furnishing a home",
    `baldai|furniture;staliukas|small table;fotelis|armchair;sofa|sofa;kilimas|carpet;lempa|lamp;spinta|wardrobe;spintelė|cupboard;lentyna|shelf;daiktas|thing;raktas|key;paveikslas|picture;laikrodis|clock / watch;šaldytuvas|refrigerator;kompiuteris|computer;televizorius|television;internetas|internet`,
  ],
  [
    4,
    88,
    "Household essentials",
    `rankšluostis|towel;veidrodis|mirror;dantų šepetukas|toothbrush;dantų pasta|toothpaste;patalynė|bedding;šiukšlių dėžė|rubbish bin;elektra|electricity;radiatorius|radiator;mokesčiai|fees / utility charges;vanduo|water`,
  ],
  [
    4,
    88,
    "Describe your flat",
    `mažas|small (masculine);didelis|large (masculine);šiltas|warm (masculine);gražus|beautiful (masculine);tvarkingas|tidy (masculine);naujas|new (masculine);jaukus|cosy (masculine);švarus|clean (masculine);patogus|comfortable (masculine);triukšmingas|noisy (masculine);ramus|quiet (masculine)`,
  ],
  [
    4,
    88,
    "Things to do at home",
    `atidaryti|to open;uždaryti|to close;įjungti|to switch on;išjungti|to switch off;galėti|to be able to;išsinuomoti|to rent for oneself;nuomoti|to rent out;padėti|to help;turėti|to have;tvarkyti|to tidy;kviesti|to invite;ateiti|to come;atvažiuoti|to arrive by vehicle;ant|on;tarp|between;vidury|in the middle of;sugesti|to break down;santechnikas|plumber;valyti|to clean`,
  ],
  [
    5,
    110,
    "Arts and evenings out",
    `laisvalaikis|free time;vakarėlis|party;gimtadienis|birthday;filmas|film;spektaklis|play / performance;muzika|music;džiazas|jazz;rokas|rock music;klasikinė muzika|classical music;koncertas|concert;opera|opera;baletas|ballet;salė|hall;parteris|stalls (theatre seating);eilė|row;vieta|seat / place`,
  ],
  [
    5,
    110,
    "Sport and the outdoors",
    `sportas|sport;krepšinis|basketball;futbolas|football;tenisas|tennis;stadionas|stadium;baseinas|swimming pool;ledo arena|ice rink;kaimas|village / countryside;sodyba|country home;ežeras|lake;jūra|sea;paplūdimys|beach;kalnas|mountain;ekskursija|excursion;kelionė|trip`,
  ],
  [
    5,
    110,
    "Travelling and the seasons",
    `aikštelė|bus station platform;peronas|railway platform;kelias|road;lėktuvas|plane;laivas|ship;keltas|ferry;tvarkaraštis|timetable;kasa|ticket office;pavasaris|spring;ruduo|autumn;atostogos|holidays;pavargęs|tired (male);pavargusi|tired (female);paprastai|usually;labai|very;labiau|more;labiausiai|most`,
  ],
  [
    5,
    110,
    "Holiday actions",
    `laiškas|letter;atvirukas|postcard;elektroninis laiškas|email;siųsti|to send;gauti|to receive;atostogauti|to be on holiday;daryti|to do / make;daryti mankštą|to exercise;veikti|to do (an activity);atvykti|to arrive;išvykti|to depart;skristi|to fly;eiti pasivaikščioti|to go for a walk;grįžti|to return;mokėti|to know how;mėgti|to like`,
  ],
  [
    5,
    110,
    "Hobbies in words",
    `klausyti|to listen;rašyti|to write;miegoti|to sleep;sportuoti|to do sport;žiūrėti|to watch;bėgioti|to jog;čiuožinėti|to skate;plaukioti|to go swimming;žvejoti|to fish;slidinėti|to ski;važinėti dviračiu|to ride a bicycle`,
  ],
  [
    6,
    134,
    "University life",
    `studijos|studies;bakalauro studijos|bachelor’s studies;magistrantūra|master’s studies;fakultetas|faculty;katedra|department;kursas|year of university studies;kursai|courses;paskaita|lecture;pertrauka|break;seminaras|seminar;egzaminas|exam;raštu|in writing;žodžiu|orally;vidurio testas|midterm test;baigiamasis testas|final test;kreditas|credit`,
  ],
  [
    6,
    134,
    "Study tasks and equipment",
    `referatas|paper / report;kursinis darbas|term paper;bakalauro darbas|bachelor’s thesis;magistro darbas|master’s thesis;prezentacija|presentation;rengti prezentaciją|to prepare a presentation;namų darbas|homework;daryti namų darbą|to do homework;žodynas|dictionary;pieštukas|pencil;tušinukas|pen;puslapis|page;pratimas|exercise;užduotis|task;pavyzdys|example;pavyzdžiui|for example;kopija|copy;stipendija|scholarship;semestras|semester;rudens semestras|autumn semester;pavasario semestras|spring semester`,
  ],
  [
    6,
    134,
    "Subjects to study",
    `dailė|fine arts;dizainas|design;ekonomika|economics;filologija|philology;istorija|history;medicina|medicine (field of study);politologija|political science;teisė|law;vadyba|management;verslas|business;žurnalistika|journalism`,
  ],
  [
    6,
    134,
    "Managing your studies",
    `išlaikyti egzaminą|to pass an exam;neišlaikyti egzamino|to fail an exam;perlaikyti egzaminą|to retake an exam;prasidėti|to begin;baigtis|to end;mokytis|to learn;vėluoti|to be late;skubėti|to hurry;paklausti|to ask a question;palaukti|to wait;spausdinti|to print;mėnuo|month`,
  ],
  [
    6,
    134,
    "At work",
    `profesija|profession;darbovietė|workplace;mokykla|school;įmonė|company;ligoninė|hospital;poliklinika|clinic;darbuotojas|employee (male);darbuotoja|employee (female);darbo sutartis|employment contract;pasirašyti|to sign;parašas|signature;anketa|form;vertimų biuras|translation office;kabinetas|office room;direktorius|director (male);direktorė|director (female);vedėjas|head of a department (male);sekretorius|secretary (male);sekretorė|secretary (female);administratorius|administrator (male);administratorė|administrator (female);kolega|colleague (male);kolegė|colleague (female)`,
  ],
  [
    6,
    134,
    "Professions",
    `mokytojas|teacher (male);mokytoja|teacher (female);vairuotojas|driver (male);vairuotoja|driver (female);gydytojas|doctor (male);gydytoja|doctor (female);vertėjas|translator (male);vertėja|translator (female);istorikas|historian (male);filologas|philologist (male);politologas|political scientist (male);žurnalistas|journalist (male);ekonomistas|economist (male);muzikantas|musician (male);teisininkas|lawyer (male);dainininkas|singer (male);dailininkas|artist (male);ūkininkas|farmer (male);vadybininkas|manager (male);verslininkas|businessman;verslininkė|businesswoman;aktorius|actor;aktorė|actress;inžinierius|engineer (male);socialinis darbuotojas|social worker (male);socialinė darbuotoja|social worker (female);IT specialistas|IT specialist (male);pensininkas|pensioner (male);namų šeimininkė|homemaker (female)`,
  ],
  [
    6,
    134,
    "A working day",
    `komandiruotė|business trip;važiuoti į komandiruotę|to go on a business trip;darbo laikas|working hours;darbo diena|working day;poilsio diena|day off;darbo telefonas|work phone;namų telefonas|home phone;mobilusis telefonas|mobile phone;skambinti|to call;atlyginimas|salary;alga|pay;užsiėmęs|busy (male);užsiėmusi|busy (female)`,
  ],
  [
    7,
    154,
    "People and family status",
    `žmogus|person;žmonės|people;vaikas|child;vaikai|children;mergaitė|girl;berniukas|boy;mergina|young woman / girlfriend;vaikinas|young man / boyfriend;moteris|woman;vyras|man;šeiminė padėtis|marital status;ištekėjusi|married (woman);neištekėjusi|unmarried (woman);vedęs|married (man);nevedęs|unmarried (man);išsiskyręs|divorced (man);išsiskyrusi|divorced (woman);našlys|widower;našlė|widow;miręs|deceased (male);mirusi|deceased (female)`,
  ],
  [
    7,
    154,
    "The extended family",
    `šeima|family;motina|mother (formal noun);tėvas|father (formal noun);tėvai|parents;pamotė|stepmother;patėvis|stepfather;duktė|daughter;dukra|daughter (alternative noun);močiutė|grandma;seneliai|grandparents;anūkas|grandson;anūkė|granddaughter;giminės|relatives;teta|aunt;dėdė|uncle;pusseserė|cousin (female);pusbrolis|cousin (male);sūnėnas|nephew;dukterėčia|niece`,
  ],
  [
    7,
    154,
    "Family events and actions",
    `šventė|celebration;proga|occasion;jubiliejus|anniversary;vestuvės|wedding;pinigai|money;gimti|to be born;mirti|to die;mylėti|to love;švęsti|to celebrate;dovanoti|to give a gift;pirkti|to buy;atrodyti|to look / seem;kartu|together`,
  ],
  [
    7,
    154,
    "Describe appearance",
    `aukštas|tall (masculine);žemas|short (height, masculine);stambus|heavily built (masculine);lieknas|slim (masculine);jaunas|young (masculine);vidutinio amžiaus|middle-aged;šviesus|fair (appearance, masculine);tamsus|dark (appearance, masculine);panašus|similar (masculine);charakteris|character`,
  ],
  [
    7,
    154,
    "Describe character",
    `geras|good (masculine);blogas|bad (masculine);linksmas|cheerful (masculine);liūdnas|sad (masculine);greitas|fast (masculine);lėtas|slow (masculine);įdomus|interesting (masculine);nuobodus|boring (masculine);protingas|clever (masculine);kvailas|foolish (masculine);darbštus|hard-working (masculine);tingus|lazy (masculine);tinginys|lazy person (male);mielas|dear / lovely (masculine);draugiškas|friendly (masculine);malonus|pleasant (masculine);mandagus|polite (masculine);nuoširdus|sincere (masculine);tylus|quiet / silent (masculine);piktas|angry (masculine)`,
  ],
  [
    8,
    178,
    "Weather forecast",
    `oras|weather;orų prognozė|weather forecast;saulė|sun;saulėtas|sunny (masculine);debesuotas|cloudy (masculine);lyti|to rain;lietus|rain;perkūnija|thunderstorm;lietus su perkūnija|rain with thunderstorms;snigti|to snow;sniegas|snow;šlapdriba|sleet;vėjas|wind;rytai|east;vakarai|west;šiaurė|north;pietūs|south;silpnas|weak (masculine);temperatūra|temperature;laipsnis|degree;šiluma|warmth;šaltis|cold (noun);plius trys|plus three;minus dešimt|minus ten`,
  ],
  [
    8,
    178,
    "Clothes for every day",
    `drabužiai|clothes;moteriški drabužiai|women’s clothes;vyriški drabužiai|men’s clothes;vaikiški drabužiai|children’s clothes;džinsai|jeans;kelnės|trousers;šortai|shorts;marškiniai|shirt;marškinėliai|T-shirt;kostiumas|suit (men’s);kostiumėlis|suit (women’s);džemperis|sweatshirt;sijonas|skirt;palaidinė|blouse;švarkas|blazer;švarkelis|women’s blazer;striukė|jacket;paltas|coat`,
  ],
  [
    8,
    178,
    "Shoes and accessories",
    `šalikas|scarf;kepurė|cap;pirštinės|gloves;kojinės|socks;pėdkelnės|tights;avalynė|footwear;batai|shoes / boots;žieminiai batai|winter boots;bateliai|shoes;basutės|sandals;sportbačiai|trainers;kuprinė|backpack;rankinė|bag;rankinukas|handbag;skėtis|umbrella;piniginė|wallet;akiniai|glasses;saulės akiniai|sunglasses`,
  ],
  [
    8,
    178,
    "Materials and labels",
    `etiketė|label;dydis|size;nuolaida|discount;procentas|percent;kvitas|receipt;medvilnė|cotton;medvilninis|cotton (adjective, masculine);vilna|wool;vilnonis|woollen (masculine);linas|linen;lininis|linen (adjective, masculine);oda|leather;odinis|leather (adjective, masculine);šilkas|silk;šilkinis|silk (adjective, masculine)`,
  ],
  [
    8,
    178,
    "Colour and fit",
    `madingas|fashionable (masculine);storas|thick (masculine);plonas|thin (masculine);ilgas|long (masculine);trumpas|short (masculine);spalva|colour;geltonas|yellow (masculine);pilkas|grey (masculine);rausvas|pink (masculine);rudas|brown (masculine);oranžinis|orange (colour, masculine);violetinis|purple (masculine);šviesiai|light (colour modifier);tamsiai|dark (colour modifier)`,
  ],
  [
    8,
    178,
    "Shopping actions",
    `dėvėti|to wear clothes;avėti|to wear shoes;nusipirkti|to buy for oneself;pasiimti|to take along;grąžinti|to return an item;pakeisti|to exchange;pasimatuoti|to try on;apsirengti|to get dressed;nusirengti|to undress;tikti|to fit / suit;įdėti kortelę|to insert a card;ištraukti kortelę|to remove a card;pridėti kortelę|to tap a card;bekontaktė kortelė|contactless card`,
  ],
  [
    9,
    196,
    "The body",
    `kūnas|body;akis|eye;akys|eyes;ausis|ear;ausys|ears;nosis|nose;dantys|teeth;širdis|heart;kraujas|blood;skrandis|stomach (organ);nugara|back;pirštas|finger;sveikata|health`,
  ],
  [
    9,
    196,
    "Illness and symptoms",
    `sirgti|to be ill;sveikti|to recover;sveikas|healthy (masculine);jaustis|to feel;peršalti|to catch a cold;kosėti|to cough;skaudėti|to hurt;susilaužyti|to break a body part;liga|illness;gripas|flu;virusas|virus;sloga|runny nose;bronchitas|bronchitis;plaučių uždegimas|pneumonia;uždegimas|inflammation;alergiškas|allergic (masculine);gulėti|to lie down;gulėti ligoninėje|to be in hospital`,
  ],
  [
    9,
    196,
    "People at the clinic",
    `šeimos gydytojas|family doctor (male);slaugytojas|nurse (male);slaugytoja|nurse (female);akių gydytojas|eye doctor (male);ausų, nosies, gerklės gydytojas|ENT doctor (male);odontologas|dentist (male);odontologė|dentist (female);traumatologas|trauma specialist (male);užsiregistruoti|to register / make an appointment;tyrimai|medical tests;daryti tyrimus|to carry out tests;rentgeno nuotrauka|X-ray;pamatuoti kraujospūdį|to measure blood pressure;skiepai|vaccinations;pasiskiepyti|to get vaccinated`,
  ],
  [
    9,
    196,
    "At the pharmacy counter",
    `receptas|prescription;vaistažolių arbata|herbal tea;vaistai nuo skausmo|pain medicine;vaistai nuo temperatūros|fever medicine;vaistai nuo slogos|cold medicine;sirupas nuo kosulio|cough syrup;purškalas|spray;pastilės|lozenges;lašai|drops;tabletė|tablet;vitaminai|vitamins;gerti vaistus|to take medicine;prieš valgį|before a meal;po valgio|after a meal;šaukštas|spoon;šaukštelis|teaspoon;nedarbingumo pažymėjimas|sick leave certificate;sveikatos draudimas|health insurance;asmens dokumentas|identity document;greitai|quickly;lėtai|slowly;blogai|badly;daug|much / many;mažai|little / few`,
  ],
  [
    10,
    212,
    "Family celebrations",
    `vardadienis|name day;krikštynos|christening;svečias|guest (male);viešnia|guest (female);dovana|gift;tortas|cake;žvakutė|small candle;žaidimas|game;valstybinės šventės|public holidays;kalendorinės šventės|calendar holidays;Naujieji metai|New Year;sutikti Naujuosius metus|to see in the New Year;fejerverkai|fireworks;tostas|toast (celebratory speech);sakyti|to say;pasakyti tostą|to make a toast`,
  ],
  [
    10,
    212,
    "Spring celebrations",
    `Užgavėnės|Shrovetide;kaukė|mask;blynas|pancake;kepti|to bake / fry;Nepriklausomybės diena|Independence Day;vėliava|flag;trispalvė|tricolour flag;herbas|coat of arms;himnas|anthem;Kaziuko mugė|Kaziukas Fair;suvenyras|souvenir;riestainis|ring-shaped bread;virti|to boil;dažyti|to colour / paint;susidaužti kiaušiniais|to tap eggs together;margutis|decorated Easter egg;ridenti margučius|to roll Easter eggs`,
  ],
  [
    10,
    212,
    "Summer and autumn celebrations",
    `Tarptautinė darbo diena|International Workers’ Day;Motinos diena|Mother’s Day;Tėvo diena|Father’s Day;Joninės|Midsummer festival;vainikas|wreath;pinti vainiką|to weave a wreath;laužas|bonfire;kurti laužą|to make a bonfire;daina|song;Valstybės diena|Statehood Day;Dainų šventė|Song Festival;Mokslo ir žinių diena|Day of Science and Knowledge;Vėlinės|All Souls’ Day;žvakė|candle;uždegti žvakę|to light a candle;kapinės|cemetery`,
  ],
  [
    10,
    213,
    "Christmas traditions",
    `Kūčios|Christmas Eve;Kūčių patiekalas|Christmas Eve dish;kūčiukai|Christmas Eve biscuits;kalėdaitis|Christmas wafer;tradicija|tradition;vakarienė|supper;silkė|herring;kisielius|thickened fruit drink;Kalėdų Senelis|Santa Claus;Kalėdų eglė|Christmas tree;žaisliukas|small toy / tree ornament;papuošalas|decoration;puošti|to decorate;mišios|Mass;melstis|to pray;sveikinti|to congratulate;linkėti|to wish;ragauti|to taste`,
  ],
  [
    10,
    213,
    "Wishes and feelings",
    `sėkmė|luck;meilė|love;laimė|happiness;džiaugsmas|joy;nuotaika|mood;gerbiamas|respected (masculine);mylimas|beloved (masculine);laimingas|happy (masculine);svarbus|important (masculine);populiarus|popular (masculine);dažniausiai|most often;nuoširdžiai|sincerely`,
  ],
];

vocabulary.push(
  [
    2,
    53,
    "Lithuanian dishes",
    `cepelinai|stuffed potato dumplings;šaltibarščiai|cold beetroot soup;koldūnai|dumplings;blyneliai|small pancakes;valgiaraštis|menu;desertas|dessert;mineralinis vanduo|mineral water;bulviniai blynai|potato pancakes`,
  ],
  [
    2,
    60,
    "Food and traditions",
    `valgis|meal / dish;miškas|forest;uoga|berry;uogienė|jam;rūgpienis|soured milk;kefyras|kefir;degtinė|vodka;midus|mead;žolelės|herbs;grybauti|to pick mushrooms;uogauti|to pick berries`,
  ],
  [
    3,
    65,
    "Everyday public signs",
    `Darbo laikas|Opening hours;Spauskite|Press (formal);Laukite|Wait (formal);Kasa laikinai nedirba|The ticket office is temporarily closed;Bankomatas neveikia|The ATM is out of order`,
  ],
  [
    4,
    89,
    "Signs in a building",
    `Prašom uždaryti duris|Please close the door;Uždaryta|Closed;Atidaryta|Open;Liftas neveikia|The lift is out of order;Pagalbos telefonas|Emergency telephone`,
  ],
  [
    5,
    113,
    "Time around a trip",
    `žiema|winter;vasara|summer;poryt|the day after tomorrow;vakar|yesterday;užvakar|the day before yesterday;pernai|last year;kitą savaitę|next week;aną savaitgalį|last weekend;kitais metais|next year;dviračių nuoma|bicycle hire`,
  ],
  [
    6,
    135,
    "Signs at work and university",
    `Dekanatas|Dean’s office;Priėmimo valandos|Consultation hours;Studentų atstovybė|Student representation;Tarnybinis įėjimas|Staff entrance;Nedarbo diena|Non-working day;Pietų pertrauka|Lunch break`,
  ],
  [
    8,
    179,
    "Read shop signs",
    `Stumti|Push;Traukti|Pull;Išpardavimas|Sale;Matavimosi kabinos|Fitting rooms;Ypatingas pasiūlymas|Special offer;Banko kortelėmis neaptarnaujame|We do not accept bank cards`,
  ],
  [
    9,
    197,
    "Find your way in a clinic",
    `Registratūra|Reception / registration desk;Registracija pas šeimos gydytoją|Registration for the family doctor;Receptiniai vaistai|Prescription medicine;Greitoji pagalba|Ambulance;Šeimos gydytoja|Family doctor (female)`,
  ],
);
